# Generated by Django 4.1.7 on 2023-04-28 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                default=0,
                related_name="userfollowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                blank=True,
                default=0,
                related_name="userfollower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
