version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
    ports:
      - 80:80

  emotional_diary:
    image: emotional_diary
    container_name: emotional_diary_service
    networks:
      - network
    volumes:
      - static-volume:/djangoproject/__collect_static
    command: >
      bash -c "gunicorn emotional_diary.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
               

networks:
  network:

volumes:
  static-volume:
  media-volume: