# Generated by Django 4.1.7 on 2023-03-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="like",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
