# Generated by Django 4.1.7 on 2023-03-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0002_alter_diary_like_alter_diary_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="diary",
        ),
        migrations.AddField(
            model_name="diary",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diaryapp.comment",
            ),
        ),
    ]
