# Generated by Django 4.1.7 on 2023-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0005_rename_comment_comment_diary"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="angry",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="disgust",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="fear",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="happiness",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="neutral",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="sadness",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="diary",
            name="surprise",
            field=models.FloatField(default=0),
        ),
    ]
